### ISSUE TITLE
Ticking Entity

### ISSUE THREAD

**Issue by ghost** [cleannrooster/Spellblade#1]
I am using this mod on a multiplayer server. When I'm alone on the server, I can use the blade flurry spell fine. However, if someone else is online, the server crashes. Other spells seem to work fine.

[crash-2022-07-18_04.47.40-server.txt](https://github.com/cleannrooster/Spellblade/files/9129517/crash-2022-07-18_04.47.40-server.txt)

**Comment by cleannrooster** [comment]
Just fixed it, will have a patch out soon
