### ISSUE TITLE
"playerMana" is null

### ISSUE THREAD

**Issue by ghost** [cleannrooster/Spellblade#2]
It seems like this problem only happens if I'm in the Nether or End and die. I can't rejoin the server once this happens and I have to clear my player data to join again.

[crash-2022-07-23_23.16.54-client.txt](https://github.com/cleannrooster/Spellblade/files/9175055/crash-2022-07-23_23.16.54-client.txt)

**Comment by cleannrooster** [comment]
I haven't been able to reproduce this bug, so i'm not sure what's causing it. In my experience though I have been crashed out of the game with certain versions of forge with the same error, so maybe try it with different versions of forge and see what happens. I did try it with version 60, the version you're on, but I didn't get crashed out of the game.

**Comment by ghost** [comment]
I just tried it in a single player world and didn't get the crash either. Must be a server problem.

**Comment by ghost** [comment]
Never mind! I just had it happen in a single player world. I killed the Ender Dragon and jumped in the portal while holding the Spellblade and it gave the same error. I'll try other Forge versions, though.

**Comment by cleannrooster** [comment]
I know it's late and the bug hasn't been confirmed, but theoretically with the new way I assign Ward to players, it should be impossible for it to be null.
